# Specify the AI provider
provider: claudeai

# Your Claude AI API key
apiKey: your-claudeai-api-key

# Claude AI client configuration
configuration:
  baseUrl: https://api.anthropic.com
  headers:
    Anthropic-Version: 2023-06-01

# Default request options for the Claude AI API
defaultRequestOptions:
  model: claude-v1
  temperature: 0.7
  maxTokensToSample: 150
  # Additional parameters specific to Claude AI